# coding: utf-8
from sqlalchemy import Column, Date, DateTime, Integer, Numeric, String, text
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class DmsZkMatterDetail(Base):
    __tablename__ = 'dms_zk_matter_detail'

    pk_id = Column(Integer, primary_key=True)
    query_date = Column(Date)
    period_id = Column(String(32))
    period_name = Column(String(32))
    period_flag = Column(String(1))
    week_start_date = Column(Date)
    week_end_date = Column(Date)
    cla_year = Column(String(32))
    city_id = Column(Integer)
    city_name = Column(String(32))
    dept_id = Column(String(64))
    dept_name = Column(String(500))
    resource_qty = Column(Numeric(64, 0))
    new_signed_qty = Column(Numeric(64, 0))
    total_signed_qty = Column(Numeric(64, 0))
    conversion_ratio = Column(Numeric(64, 8))
    signed_amt = Column(Numeric(64, 8))
    new_signed_amt = Column(Numeric(64, 8))
    continue_signed_amt = Column(Numeric(64, 8))
    study_hours_amt = Column(Numeric(64, 8))
    study_hours = Column(Numeric(64, 8))
    payment_qty = Column(Numeric(64, 0))
    online_stu_qty = Column(Numeric(64, 0))
    online_qty = Column(Numeric(64, 0))
    continue_signed_qty = Column(Numeric(64, 0))
    apply_refund_qty = Column(Numeric(64, 0))
    refund_qty = Column(Numeric(64, 0))
    on_class_ratio = Column(Numeric(64, 8))
    full_class_ratio = Column(Numeric(64, 8))
    suspend_class_ratio = Column(Numeric(64, 8))
    seat_qty = Column(Numeric(64, 0))
    seat_used_ratio = Column(Numeric(64, 8))
    emp_qty = Column(Numeric(64, 0))
    emp_capacity_qty = Column(Numeric(64, 0))
    ly_resource_qty = Column(Numeric(64, 0))
    ly_new_signed_qty = Column(Numeric(64, 0))
    ly_total_signed_qty = Column(Numeric(64, 0))
    ly_conversion_ratio = Column(Numeric(64, 8))
    ly_signed_amt = Column(Numeric(64, 8))
    ly_new_signed_amt = Column(Numeric(64, 8))
    ly_continue_signed_amt = Column(Numeric(64, 8))
    ly_study_hours_amt = Column(Numeric(64, 8))
    ly_study_hours = Column(Numeric(64, 8))
    ly_payment_qty = Column(Numeric(64, 0))
    ly_online_stu_qty = Column(Numeric(64, 0))
    ly_online_qty = Column(Numeric(64, 0))
    ly_continue_signed_qty = Column(Numeric(64, 0))
    ly_apply_refund_qty = Column(Numeric(64, 0))
    ly_refund_qty = Column(Numeric(64, 0))
    ly_on_class_ratio = Column(Numeric(64, 8))
    ly_full_class_ratio = Column(Numeric(64, 8))
    ly_suspend_class_ratio = Column(Numeric(64, 8))
    ly_seat_qty = Column(Numeric(64, 0))
    ly_seat_used_ratio = Column(Numeric(64, 8))
    ly_emp_qty = Column(Numeric(64, 0))
    ly_emp_capacity_qty = Column(Numeric(64, 0))
    yty_resource_qty = Column(Numeric(64, 8))
    yty_new_signed_qty = Column(Numeric(64, 8))
    yty_total_signed_qty = Column(Numeric(64, 0))
    yty_conversion_ratio = Column(Numeric(64, 8))
    yty_signed_amt = Column(Numeric(64, 8))
    yty_new_signed_amt = Column(Numeric(64, 8))
    yty_continue_signed_amt = Column(Numeric(64, 8))
    yty_study_hours_amt = Column(Numeric(64, 8))
    yty_study_hours = Column(Numeric(64, 8))
    yty_payment_qty = Column(Numeric(64, 8))
    yty_online_stu_qty = Column(Numeric(64, 8))
    yty_online_qty = Column(Numeric(64, 8))
    yty_continue_signed_qty = Column(Numeric(64, 8))
    yty_apply_refund_qty = Column(Numeric(64, 8))
    yty_refund_qty = Column(Numeric(64, 8))
    yty_on_class_ratio = Column(Numeric(64, 8))
    yty_full_class_ratio = Column(Numeric(64, 8))
    yty_suspend_class_ratio = Column(Numeric(64, 8))
    yty_seat_qty = Column(Numeric(64, 8))
    yty_seat_used_ratio = Column(Numeric(64, 8))
    yty_emp_qty = Column(Numeric(64, 0))
    yty_emp_capacity_qty = Column(Numeric(64, 0))
    update_date = Column(DateTime, server_default=text("CURRENT_TIMESTAMP"))
